language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

env:
  - SXGEO_DB=SxGeo.dat SXGEO_CITY_DB=SxGeoCity.dat

before_script:
  - wget http://sypexgeo.net/files/SxGeoCountry.zip && unzip SxGeoCountry.zip
  - wget http://sypexgeo.net/files/SxGeoCity_utf8.zip && unzip SxGeoCity_utf8.zip

addons:
  code_climate:
    repo_token: 15e49d47a87a130d4a3cde0bb2ce14fe9053f525e92495a215027aff3e552368
