language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

env:
  - SYPEXGEO_CITY_MAX_DB=sypexgeo_city_max.dat

before_script:
  - '[ -f sypexgeo_city_max.dat ] || (wget http://sypexgeo.net/files/SxGeoCityMax_utf8.zip && unzip SxGeoCityMax_utf8.zip && mv SxGeoCityMax.dat sypexgeo_city_max.dat)'

addons:
  code_climate:
    repo_token: 15e49d47a87a130d4a3cde0bb2ce14fe9053f525e92495a215027aff3e552368 
